name: Deploy to Streamlit Community Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pandas openpyxl requests beautifulsoup4
        
    - name: Test Streamlit apps
      run: |
        # Test if apps can be imported without errors
        python -c "import eden_integrated_launcher"
        python -c "import eden_quiz_app"
        echo "✅ All apps imported successfully"
